import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// The Qwik server runtime imports the bare specifier "@qwik-client-manifest".
// In a production Node server (without the Vite dev plugin resolving it), that
// virtual module must resolve to a real package. The real client manifest is
// inlined into server/entry.ssr.js and merged per request, so an empty object
// here is sufficient for SSR/resumption.
const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, "..");
const pkgDir = join(projectRoot, "node_modules", "@qwik-client-manifest");

mkdirSync(pkgDir, { recursive: true });
writeFileSync(
  join(pkgDir, "package.json"),
  `${JSON.stringify(
    { name: "@qwik-client-manifest", type: "module", main: "index.mjs" },
    null,
    2,
  )}\n`,
);
writeFileSync(
  join(pkgDir, "index.mjs"),
  `// Generated by scripts/postbuild.mjs. The real client manifest is inlined into\nexport const manifest = {};\n`,
);

console.log("Created @qwik-client-manifest shim for the Node server runtime.");
