/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  admin: {
    Admin: () => import('#controllers/admin/admin_controller'),
    AdminRoutes: () => import('#controllers/admin/admin_routes'),
    AdminService: () => import('#controllers/admin/admin_service'),
  },
  analytics: {
    Analytics: () => import('#controllers/analytics/analytics_controller'),
    AnalyticsRoutes: () => import('#controllers/analytics/analytics_routes'),
    AnalyticsService: () => import('#controllers/analytics/analytics_service'),
    AnalyticsValidators: () => import('#controllers/analytics/analytics_validators'),
  },
  audit: {
    Audit: () => import('#controllers/audit/audit_controller'),
    AuditRoutes: () => import('#controllers/audit/audit_routes'),
    AuditService: () => import('#controllers/audit/audit_service'),
  },
  auth: {
    Auth: () => import('#controllers/auth/auth_controller'),
    AuthRoutes: () => import('#controllers/auth/auth_routes'),
    AuthService: () => import('#controllers/auth/auth_service'),
    AuthValidators: () => import('#controllers/auth/auth_validators'),
    services: {
      AuthCookiesService: () => import('#controllers/auth/services/auth_cookies_service'),
      CaptchaService: () => import('#controllers/auth/services/captcha_service'),
      DeviceInfoService: () => import('#controllers/auth/services/device_info_service'),
      EmailVerificationService: () => import('#controllers/auth/services/email_verification_service'),
      SessionService: () => import('#controllers/auth/services/session_service'),
    },
  },
  blog: {
    Blog: () => import('#controllers/blog/blog_controller'),
    BlogRoutes: () => import('#controllers/blog/blog_routes'),
    BlogService: () => import('#controllers/blog/blog_service'),
    BlogValidators: () => import('#controllers/blog/blog_validators'),
  },
  cart: {
    Cart: () => import('#controllers/cart/cart_controller'),
    CartRoutes: () => import('#controllers/cart/cart_routes'),
    CartService: () => import('#controllers/cart/cart_service'),
    CartValidators: () => import('#controllers/cart/cart_validators'),
  },
  coupon: {
    Coupon: () => import('#controllers/coupon/coupon_controller'),
    CouponRoutes: () => import('#controllers/coupon/coupon_routes'),
    CouponService: () => import('#controllers/coupon/coupon_service'),
    CouponValidators: () => import('#controllers/coupon/coupon_validators'),
  },
  giftCard: {
    GiftCard: () => import('#controllers/gift_card/gift_card_controller'),
    GiftCardRoutes: () => import('#controllers/gift_card/gift_card_routes'),
    GiftCardService: () => import('#controllers/gift_card/gift_card_service'),
    GiftCardValidators: () => import('#controllers/gift_card/gift_card_validators'),
  },
  health: {
    Health: () => import('#controllers/health/health_controller'),
    HealthRoutes: () => import('#controllers/health/health_routes'),
  },
  hero: {
    Hero: () => import('#controllers/hero/hero_controller'),
    HeroRoutes: () => import('#controllers/hero/hero_routes'),
    HeroService: () => import('#controllers/hero/hero_service'),
    HeroValidators: () => import('#controllers/hero/hero_validators'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  newArrival: {
    NewArrival: () => import('#controllers/new_arrival/new_arrival_controller'),
    NewArrivalRoutes: () => import('#controllers/new_arrival/new_arrival_routes'),
    NewArrivalService: () => import('#controllers/new_arrival/new_arrival_service'),
    NewArrivalValidators: () => import('#controllers/new_arrival/new_arrival_validators'),
  },
  notification: {
    EmailTemplate: () => import('#controllers/notification/email_template_controller'),
    EmailTemplateRoutes: () => import('#controllers/notification/email_template_routes'),
    EmailTemplateService: () => import('#controllers/notification/email_template_service'),
    EmailTemplateValidators: () => import('#controllers/notification/email_template_validators'),
    Notification: () => import('#controllers/notification/notification_controller'),
    NotificationQueue: () => import('#controllers/notification/notification_queue'),
    NotificationRoutes: () => import('#controllers/notification/notification_routes'),
    NotificationService: () => import('#controllers/notification/notification_service'),
    NotificationValidators: () => import('#controllers/notification/notification_validators'),
    RabbitmqService: () => import('#controllers/notification/rabbitmq_service'),
  },
  order: {
    Order: () => import('#controllers/order/order_controller'),
    OrderRoutes: () => import('#controllers/order/order_routes'),
    OrderService: () => import('#controllers/order/order_service'),
    OrderValidators: () => import('#controllers/order/order_validators'),
  },
  product: {
    CatalogExtraService: () => import('#controllers/product/catalog_extra_service'),
    Product: () => import('#controllers/product/product_controller'),
    ProductRoutes: () => import('#controllers/product/product_routes'),
    ProductService: () => import('#controllers/product/product_service'),
    ProductValidators: () => import('#controllers/product/product_validators'),
  },
  Profile: () => import('#controllers/profile_controller'),
  review: {
    Review: () => import('#controllers/review/review_controller'),
    ReviewRoutes: () => import('#controllers/review/review_routes'),
    ReviewService: () => import('#controllers/review/review_service'),
    ReviewValidators: () => import('#controllers/review/review_validators'),
  },
  settings: {
    Settings: () => import('#controllers/settings/settings_controller'),
    SettingsRoutes: () => import('#controllers/settings/settings_routes'),
    SettingsService: () => import('#controllers/settings/settings_service'),
    SettingsValidators: () => import('#controllers/settings/settings_validators'),
  },
  user: {
    User: () => import('#controllers/user/user_controller'),
    UserRoutes: () => import('#controllers/user/user_routes'),
    UserService: () => import('#controllers/user/user_service'),
    UserValidators: () => import('#controllers/user/user_validators'),
  },
  wishlist: {
    Wishlist: () => import('#controllers/wishlist/wishlist_controller'),
    WishlistRoutes: () => import('#controllers/wishlist/wishlist_routes'),
    WishlistService: () => import('#controllers/wishlist/wishlist_service'),
    WishlistValidators: () => import('#controllers/wishlist/wishlist_validators'),
  },
}
