import { ignore } from '@adonisjs/core/dependencies'
import router from '@adonisjs/core/services/router'

const HealthController = () => import('#controllers/health_controller')
const AuthController = () => import('#controllers/auth_controller')
const ProductController = () => import('#controllers/product_controller')
const CartController = () => import('#controllers/cart_controller')
const WishlistController = () => import('#controllers/wishlist_controller')
const OrderController = () => import('#controllers/order_controller')
const ReviewController = () => import('#controllers/review_controller')
const BlogController = () => import('#controllers/blog_controller')
const AdminController = () => import('#controllers/admin_controller')
const SettingsController = () => import('#controllers/settings_controller')
const HeroController = () => import('#controllers/hero_controller')
const NewArrivalController = () => import('#controllers/new_arrival_controller')
const GiftCardController = () => import('#controllers/gift_card_controller')
const NotificationController = () => import('#controllers/notification_controller')
const AuditController = () => import('#controllers/audit_controller')
const AnalyticsController = () => import('#controllers/analytics_controller')
const AppController = () => import('#controllers/app_controller')

router
  .group(() => {
    router.get('/health', [HealthController, 'index'])
    router.get('/products/featured', [ProductController, 'featured'])
    router.get('/blog', [BlogController, 'index'])
    router.get('/blog/:slug', [BlogController, 'show'])
    router.get('/review/featured', [ReviewController, 'featured'])
    router.get('/hero/active', [HeroController, 'active'])
    router.get('/new-arrivals/active', [NewArrivalController, 'active'])
    router.get('/gift-card/balance', [GiftCardController, 'balance'])
    router.get('/settings', [SettingsController, 'show'])
    router.post('/auth/register', [AuthController, 'register'])
    router.post('/auth/login', [AuthController, 'login'])
    router.post('/auth/logout', [AuthController, 'logout'])
    router.post('/auth/refresh', [AuthController, 'refresh'])
    router.post('/order/checkout-session', [OrderController, 'checkoutSession'])
    router.post('/order/verify-payment', [OrderController, 'verifyPayment'])
    router.post('/gift-card/redeem', [GiftCardController, 'redeem'])
  })
  .prefix('/api/v1')

router
  .group(() => {
    router.get('/auth/session', [AuthController, 'session'])
    router.get('/auth/profile', [AuthController, 'profile'])
    router.get('/orders', [OrderController, 'index'])
    router.get('/orders/:id', [OrderController, 'show'])
    router.post('/orders', [OrderController, 'store'])
    router.get('/cart', [CartController, 'index'])
    router.post('/cart', [CartController, 'add'])
    router.patch('/cart/:productId', [CartController, 'update'])
    router.delete('/cart/:productId', [CartController, 'remove'])
    router.get('/wishlist', [WishlistController, 'index'])
    router.post('/wishlist', [WishlistController, 'add'])
    router.delete('/wishlist/:productId', [WishlistController, 'remove'])
    router.get('/notification', [NotificationController, 'index'])
    router.get('/notification/unread-count', [NotificationController, 'unreadCount'])
    router.patch('/notification/:id/read', [NotificationController, 'markRead'])
    router.get('/reviews', [ReviewController, 'index'])
    router.get('/reviews/product/:productId', [ReviewController, 'productReviews'])
    router.post('/reviews', [ReviewController, 'store'])
    router.get('/analytics/recently-viewed', [AnalyticsController, 'recentlyViewed'])
  })
  .prefix('/api/v1')
  .middleware(['auth'])

router
  .group(() => {
    router.get('/products/admin/all', [ProductController, 'adminIndex'])
    router.get('/orders/admin', [OrderController, 'adminIndex'])
    router.get('/admin/overview', [AdminController, 'overview'])
    router.get('/audit/log', [AuditController, 'index'])
    router.get('/audit/log/:id', [AuditController, 'show'])
    router.get('/hero', [HeroController, 'index'])
    router.post('/hero', [HeroController, 'store'])
    router.patch('/hero/:id', [HeroController, 'update'])
    router.delete('/hero/:id', [HeroController, 'destroy'])
    router.get('/new-arrivals', [NewArrivalController, 'index'])
    router.post('/new-arrivals', [NewArrivalController, 'store'])
    router.patch('/new-arrivals/:id', [NewArrivalController, 'update'])
    router.delete('/new-arrivals/:id', [NewArrivalController, 'destroy'])
    router.get('/gift-card', [GiftCardController, 'index'])
    router.post('/gift-card', [GiftCardController, 'store'])
    router.patch('/gift-card/:id', [GiftCardController, 'update'])
    router.delete('/gift-card/:id', [GiftCardController, 'destroy'])
    router.get('/notification/admin', [NotificationController, 'index'])
    router.get('/analytics/abandoned-carts', [AnalyticsController, 'abandonedCarts'])
    router.patch('/settings', [SettingsController, 'update'])
  })
  .prefix('/api/v1')
  .middleware(['auth', 'admin'])

router.get('/sitemap.xml', [AppController, 'sitemap'])
router.get('/robots.txt', [AppController, 'robots'])
