import { Env } from '@adonisjs/env'

export default await Env.create({
  NODE_ENV: Env.schema.enum(['development', 'production', 'test'] as const),
  PORT: Env.schema.number(),
  HOST: Env.schema.string({ format: 'host' }),
  APP_KEY: Env.schema.string(),
  DATABASE_URL: Env.schema.string(),
  JWT_SECRET: Env.schema.string(),
  GOOGLE_CLIENT_ID: Env.schema.string.optional(),
  SITE_URL: Env.schema.string.optional(),
  FRONTEND_URL: Env.schema.string.optional(),
  BACKEND_URL: Env.schema.string.optional(),
  API_PUBLIC_URL: Env.schema.string.optional(),
  CORS_ORIGINS: Env.schema.string.optional(),
  REDIS_URL: Env.schema.string.optional(),
  REDIS_CACHE_TTL_SECONDS: Env.schema.number.optional(),
  SMTP_HOST: Env.schema.string.optional(),
  SMTP_PORT: Env.schema.number.optional(),
  SMTP_SECURE: Env.schema.boolean.optional(),
  SMTP_USER: Env.schema.string.optional(),
  SMTP_PASS: Env.schema.string.optional(),
  EMAIL_FROM: Env.schema.string.optional(),
  RAZORPAY_KEY_ID: Env.schema.string.optional(),
  RAZORPAY_KEY_SECRET: Env.schema.string.optional(),
  RAZORPAY_WEBHOOK_SECRET: Env.schema.string.optional(),
  RAZORPAY_CURRENCY: Env.schema.string.optional(),
  STORAGE_PROVIDER: Env.schema.string.optional(),
  STORAGE_CLOUDINARY_CLOUD_NAME: Env.schema.string.optional(),
  STORAGE_CLOUDINARY_API_KEY: Env.schema.string.optional(),
  STORAGE_CLOUDINARY_API_SECRET: Env.schema.string.optional(),
  STORAGE_CLOUDINARY_FOLDER: Env.schema.string.optional(),
  STORAGE_CLOUDINARY_PUBLIC_URL: Env.schema.string.optional(),
  STORAGE_CLOUDINARY_UPLOAD_PRESET: Env.schema.string.optional(),
  STORAGE_LOCAL_UPLOADS_PATH: Env.schema.string.optional(),
  RABBITMQ_URL: Env.schema.string.optional(),
  NOTIFICATION_MAX_ATTEMPTS: Env.schema.number.optional(),
  NOTIFICATION_RETRY_INTERVAL_MS: Env.schema.number.optional(),
})
