import type { AdonisEndpoint } from '@tuyau/core/types';
import type { Registry } from './schema.d.ts';
import type { ApiDefinition } from './tree.d.ts';

const placeholder: any = {};

const routes = {
  'auth.generate_captcha': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/auth/captcha',
    tokens: [
      { old: '/api/v1/auth/captcha', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/captcha', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/captcha', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/captcha', type: 0, val: 'captcha', end: '' },
    ],
    types: placeholder as Registry['auth.generate_captcha']['types'],
  },
  'auth.login': {
    methods: ['POST'],
    pattern: '/api/v1/auth/login',
    tokens: [
      { old: '/api/v1/auth/login', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/login', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/login', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/login', type: 0, val: 'login', end: '' },
    ],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.google_auth': {
    methods: ['POST'],
    pattern: '/api/v1/auth/google',
    tokens: [
      { old: '/api/v1/auth/google', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/google', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/google', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/google', type: 0, val: 'google', end: '' },
    ],
    types: placeholder as Registry['auth.google_auth']['types'],
  },
  'auth.register': {
    methods: ['POST'],
    pattern: '/api/v1/auth/register',
    tokens: [
      { old: '/api/v1/auth/register', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/register', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/register', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/register', type: 0, val: 'register', end: '' },
    ],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.verify_email': {
    methods: ['POST'],
    pattern: '/api/v1/auth/verify-email',
    tokens: [
      { old: '/api/v1/auth/verify-email', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/verify-email', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/verify-email', type: 0, val: 'auth', end: '' },
      {
        old: '/api/v1/auth/verify-email',
        type: 0,
        val: 'verify-email',
        end: '',
      },
    ],
    types: placeholder as Registry['auth.verify_email']['types'],
  },
  'auth.resend_verification': {
    methods: ['POST'],
    pattern: '/api/v1/auth/resend-verification',
    tokens: [
      { old: '/api/v1/auth/resend-verification', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/resend-verification', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/auth/resend-verification',
        type: 0,
        val: 'auth',
        end: '',
      },
      {
        old: '/api/v1/auth/resend-verification',
        type: 0,
        val: 'resend-verification',
        end: '',
      },
    ],
    types: placeholder as Registry['auth.resend_verification']['types'],
  },
  'auth.forgot_password': {
    methods: ['POST'],
    pattern: '/api/v1/auth/forgot-password',
    tokens: [
      { old: '/api/v1/auth/forgot-password', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/forgot-password', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/forgot-password', type: 0, val: 'auth', end: '' },
      {
        old: '/api/v1/auth/forgot-password',
        type: 0,
        val: 'forgot-password',
        end: '',
      },
    ],
    types: placeholder as Registry['auth.forgot_password']['types'],
  },
  'auth.reset_password': {
    methods: ['POST'],
    pattern: '/api/v1/auth/reset-password',
    tokens: [
      { old: '/api/v1/auth/reset-password', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/reset-password', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/reset-password', type: 0, val: 'auth', end: '' },
      {
        old: '/api/v1/auth/reset-password',
        type: 0,
        val: 'reset-password',
        end: '',
      },
    ],
    types: placeholder as Registry['auth.reset_password']['types'],
  },
  'auth.session': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/auth/session',
    tokens: [
      { old: '/api/v1/auth/session', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/session', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/session', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/session', type: 0, val: 'session', end: '' },
    ],
    types: placeholder as Registry['auth.session']['types'],
  },
  'auth.refresh': {
    methods: ['POST'],
    pattern: '/api/v1/auth/refresh',
    tokens: [
      { old: '/api/v1/auth/refresh', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/refresh', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/refresh', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/refresh', type: 0, val: 'refresh', end: '' },
    ],
    types: placeholder as Registry['auth.refresh']['types'],
  },
  'auth.get_profile': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/auth/profile',
    tokens: [
      { old: '/api/v1/auth/profile', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/profile', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/profile', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/profile', type: 0, val: 'profile', end: '' },
    ],
    types: placeholder as Registry['auth.get_profile']['types'],
  },
  'auth.update_profile': {
    methods: ['PATCH'],
    pattern: '/api/v1/auth/profile',
    tokens: [
      { old: '/api/v1/auth/profile', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/profile', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/profile', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/profile', type: 0, val: 'profile', end: '' },
    ],
    types: placeholder as Registry['auth.update_profile']['types'],
  },
  'auth.change_password': {
    methods: ['POST'],
    pattern: '/api/v1/auth/change-password',
    tokens: [
      { old: '/api/v1/auth/change-password', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/change-password', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/change-password', type: 0, val: 'auth', end: '' },
      {
        old: '/api/v1/auth/change-password',
        type: 0,
        val: 'change-password',
        end: '',
      },
    ],
    types: placeholder as Registry['auth.change_password']['types'],
  },
  'auth.delete_account': {
    methods: ['DELETE'],
    pattern: '/api/v1/auth/account',
    tokens: [
      { old: '/api/v1/auth/account', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/account', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/account', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/account', type: 0, val: 'account', end: '' },
    ],
    types: placeholder as Registry['auth.delete_account']['types'],
  },
  'auth.logout': {
    methods: ['POST'],
    pattern: '/api/v1/auth/logout',
    tokens: [
      { old: '/api/v1/auth/logout', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/logout', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/logout', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/logout', type: 0, val: 'logout', end: '' },
    ],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.upload_avatar': {
    methods: ['POST'],
    pattern: '/api/v1/auth/upload-avatar',
    tokens: [
      { old: '/api/v1/auth/upload-avatar', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/upload-avatar', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/upload-avatar', type: 0, val: 'auth', end: '' },
      {
        old: '/api/v1/auth/upload-avatar',
        type: 0,
        val: 'upload-avatar',
        end: '',
      },
    ],
    types: placeholder as Registry['auth.upload_avatar']['types'],
  },
  'auth.list_sessions': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/auth/sessions',
    tokens: [
      { old: '/api/v1/auth/sessions', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/sessions', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/sessions', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/sessions', type: 0, val: 'sessions', end: '' },
    ],
    types: placeholder as Registry['auth.list_sessions']['types'],
  },
  'auth.revoke_session': {
    methods: ['DELETE'],
    pattern: '/api/v1/auth/sessions/:id',
    tokens: [
      { old: '/api/v1/auth/sessions/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/sessions/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/sessions/:id', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/sessions/:id', type: 0, val: 'sessions', end: '' },
      { old: '/api/v1/auth/sessions/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['auth.revoke_session']['types'],
  },
  'auth.list_addresses': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/auth/addresses',
    tokens: [
      { old: '/api/v1/auth/addresses', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/addresses', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/addresses', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/addresses', type: 0, val: 'addresses', end: '' },
    ],
    types: placeholder as Registry['auth.list_addresses']['types'],
  },
  'auth.create_address': {
    methods: ['POST'],
    pattern: '/api/v1/auth/addresses',
    tokens: [
      { old: '/api/v1/auth/addresses', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/addresses', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/addresses', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/addresses', type: 0, val: 'addresses', end: '' },
    ],
    types: placeholder as Registry['auth.create_address']['types'],
  },
  'auth.update_address': {
    methods: ['PATCH'],
    pattern: '/api/v1/auth/addresses/:id',
    tokens: [
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'addresses', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['auth.update_address']['types'],
  },
  'auth.remove_address': {
    methods: ['DELETE'],
    pattern: '/api/v1/auth/addresses/:id',
    tokens: [
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'auth', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 0, val: 'addresses', end: '' },
      { old: '/api/v1/auth/addresses/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['auth.remove_address']['types'],
  },
  'user.create': {
    methods: ['POST'],
    pattern: '/api/v1/users',
    tokens: [
      { old: '/api/v1/users', type: 0, val: 'api', end: '' },
      { old: '/api/v1/users', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/users', type: 0, val: 'users', end: '' },
    ],
    types: placeholder as Registry['user.create']['types'],
  },
  'user.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/users',
    tokens: [
      { old: '/api/v1/users', type: 0, val: 'api', end: '' },
      { old: '/api/v1/users', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/users', type: 0, val: 'users', end: '' },
    ],
    types: placeholder as Registry['user.find_all']['types'],
  },
  'user.find_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/users/:id',
    tokens: [
      { old: '/api/v1/users/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/users/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/users/:id', type: 0, val: 'users', end: '' },
      { old: '/api/v1/users/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['user.find_one']['types'],
  },
  'user.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/users/:id',
    tokens: [
      { old: '/api/v1/users/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/users/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/users/:id', type: 0, val: 'users', end: '' },
      { old: '/api/v1/users/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['user.update']['types'],
  },
  'user.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/users/:id',
    tokens: [
      { old: '/api/v1/users/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/users/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/users/:id', type: 0, val: 'users', end: '' },
      { old: '/api/v1/users/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['user.remove']['types'],
  },
  'product.upload_image': {
    methods: ['POST'],
    pattern: '/api/v1/products/upload-image',
    tokens: [
      { old: '/api/v1/products/upload-image', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/upload-image', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/products/upload-image',
        type: 0,
        val: 'products',
        end: '',
      },
      {
        old: '/api/v1/products/upload-image',
        type: 0,
        val: 'upload-image',
        end: '',
      },
    ],
    types: placeholder as Registry['product.upload_image']['types'],
  },
  'product.create_product': {
    methods: ['POST'],
    pattern: '/api/v1/products',
    tokens: [
      { old: '/api/v1/products', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products', type: 0, val: 'products', end: '' },
    ],
    types: placeholder as Registry['product.create_product']['types'],
  },
  'product.get_products': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/products',
    tokens: [
      { old: '/api/v1/products', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products', type: 0, val: 'products', end: '' },
    ],
    types: placeholder as Registry['product.get_products']['types'],
  },
  'product.get_admin_products': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/products/admin/all',
    tokens: [
      { old: '/api/v1/products/admin/all', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/admin/all', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/admin/all', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/admin/all', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/products/admin/all', type: 0, val: 'all', end: '' },
    ],
    types: placeholder as Registry['product.get_admin_products']['types'],
  },
  'product.get_new_arrivals': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/products/new-arrivals',
    tokens: [
      { old: '/api/v1/products/new-arrivals', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/new-arrivals', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/products/new-arrivals',
        type: 0,
        val: 'products',
        end: '',
      },
      {
        old: '/api/v1/products/new-arrivals',
        type: 0,
        val: 'new-arrivals',
        end: '',
      },
    ],
    types: placeholder as Registry['product.get_new_arrivals']['types'],
  },
  'product.get_product': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/products/:id',
    tokens: [
      { old: '/api/v1/products/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/:id', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['product.get_product']['types'],
  },
  'product.update_product': {
    methods: ['PATCH'],
    pattern: '/api/v1/products/:id',
    tokens: [
      { old: '/api/v1/products/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/:id', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['product.update_product']['types'],
  },
  'product.delete_product': {
    methods: ['DELETE'],
    pattern: '/api/v1/products/:id',
    tokens: [
      { old: '/api/v1/products/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/:id', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['product.delete_product']['types'],
  },
  'product.record_view': {
    methods: ['POST'],
    pattern: '/api/v1/products/viewed',
    tokens: [
      { old: '/api/v1/products/viewed', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'viewed', end: '' },
    ],
    types: placeholder as Registry['product.record_view']['types'],
  },
  'product.get_recently_viewed': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/products/viewed',
    tokens: [
      { old: '/api/v1/products/viewed', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'viewed', end: '' },
    ],
    types: placeholder as Registry['product.get_recently_viewed']['types'],
  },
  'product.clear_history': {
    methods: ['DELETE'],
    pattern: '/api/v1/products/viewed',
    tokens: [
      { old: '/api/v1/products/viewed', type: 0, val: 'api', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'products', end: '' },
      { old: '/api/v1/products/viewed', type: 0, val: 'viewed', end: '' },
    ],
    types: placeholder as Registry['product.clear_history']['types'],
  },
  'cart.create': {
    methods: ['POST'],
    pattern: '/api/v1/cart',
    tokens: [
      { old: '/api/v1/cart', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart', type: 0, val: 'cart', end: '' },
    ],
    types: placeholder as Registry['cart.create']['types'],
  },
  'cart.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/cart',
    tokens: [
      { old: '/api/v1/cart', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart', type: 0, val: 'cart', end: '' },
    ],
    types: placeholder as Registry['cart.find_all']['types'],
  },
  'cart.find_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/cart/:id',
    tokens: [
      { old: '/api/v1/cart/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/:id', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['cart.find_one']['types'],
  },
  'cart.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/cart/:id',
    tokens: [
      { old: '/api/v1/cart/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/:id', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['cart.update']['types'],
  },
  'cart.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/cart/:id',
    tokens: [
      { old: '/api/v1/cart/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/:id', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['cart.remove']['types'],
  },
  'cart.clear': {
    methods: ['DELETE'],
    pattern: '/api/v1/cart',
    tokens: [
      { old: '/api/v1/cart', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart', type: 0, val: 'cart', end: '' },
    ],
    types: placeholder as Registry['cart.clear']['types'],
  },
  'cart.create_guest_cart': {
    methods: ['POST'],
    pattern: '/api/v1/cart/guest',
    tokens: [
      { old: '/api/v1/cart/guest', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'guest', end: '' },
    ],
    types: placeholder as Registry['cart.create_guest_cart']['types'],
  },
  'cart.get_guest_cart': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/cart/guest',
    tokens: [
      { old: '/api/v1/cart/guest', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'guest', end: '' },
    ],
    types: placeholder as Registry['cart.get_guest_cart']['types'],
  },
  'cart.get_guest_cart_by_token': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/cart/guest/:token',
    tokens: [
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'guest', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 1, val: 'token', end: '' },
    ],
    types: placeholder as Registry['cart.get_guest_cart_by_token']['types'],
  },
  'cart.merge_guest_cart': {
    methods: ['POST'],
    pattern: '/api/v1/cart/guest/merge',
    tokens: [
      { old: '/api/v1/cart/guest/merge', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/guest/merge', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/guest/merge', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/guest/merge', type: 0, val: 'guest', end: '' },
      { old: '/api/v1/cart/guest/merge', type: 0, val: 'merge', end: '' },
    ],
    types: placeholder as Registry['cart.merge_guest_cart']['types'],
  },
  'cart.delete_guest_cart': {
    methods: ['DELETE'],
    pattern: '/api/v1/cart/guest',
    tokens: [
      { old: '/api/v1/cart/guest', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/guest', type: 0, val: 'guest', end: '' },
    ],
    types: placeholder as Registry['cart.delete_guest_cart']['types'],
  },
  'cart.delete_guest_cart_by_token': {
    methods: ['DELETE'],
    pattern: '/api/v1/cart/guest/:token',
    tokens: [
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'api', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'cart', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 0, val: 'guest', end: '' },
      { old: '/api/v1/cart/guest/:token', type: 1, val: 'token', end: '' },
    ],
    types: placeholder as Registry['cart.delete_guest_cart_by_token']['types'],
  },
  'order.handle_razorpay_webhook': {
    methods: ['POST'],
    pattern: '/api/v1/order/webhook/razorpay',
    tokens: [
      { old: '/api/v1/order/webhook/razorpay', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/webhook/razorpay', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/webhook/razorpay', type: 0, val: 'order', end: '' },
      {
        old: '/api/v1/order/webhook/razorpay',
        type: 0,
        val: 'webhook',
        end: '',
      },
      {
        old: '/api/v1/order/webhook/razorpay',
        type: 0,
        val: 'razorpay',
        end: '',
      },
    ],
    types: placeholder as Registry['order.handle_razorpay_webhook']['types'],
  },
  'order.verify_payment': {
    methods: ['POST'],
    pattern: '/api/v1/order/verify-payment',
    tokens: [
      { old: '/api/v1/order/verify-payment', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/verify-payment', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/verify-payment', type: 0, val: 'order', end: '' },
      {
        old: '/api/v1/order/verify-payment',
        type: 0,
        val: 'verify-payment',
        end: '',
      },
    ],
    types: placeholder as Registry['order.verify_payment']['types'],
  },
  'order.create_checkout_session': {
    methods: ['POST'],
    pattern: '/api/v1/order/checkout-session',
    tokens: [
      { old: '/api/v1/order/checkout-session', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/checkout-session', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/checkout-session', type: 0, val: 'order', end: '' },
      {
        old: '/api/v1/order/checkout-session',
        type: 0,
        val: 'checkout-session',
        end: '',
      },
    ],
    types: placeholder as Registry['order.create_checkout_session']['types'],
  },
  'order.preview': {
    methods: ['POST'],
    pattern: '/api/v1/order/preview',
    tokens: [
      { old: '/api/v1/order/preview', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/preview', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/preview', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/preview', type: 0, val: 'preview', end: '' },
    ],
    types: placeholder as Registry['order.preview']['types'],
  },
  'order.create': {
    methods: ['POST'],
    pattern: '/api/v1/order',
    tokens: [
      { old: '/api/v1/order', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order', type: 0, val: 'order', end: '' },
    ],
    types: placeholder as Registry['order.create']['types'],
  },
  'order.find_my_orders': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order',
    tokens: [
      { old: '/api/v1/order', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order', type: 0, val: 'order', end: '' },
    ],
    types: placeholder as Registry['order.find_my_orders']['types'],
  },
  'order.find_admin_orders': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/admin',
    tokens: [
      { old: '/api/v1/order/admin', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/admin', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/admin', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/admin', type: 0, val: 'admin', end: '' },
    ],
    types: placeholder as Registry['order.find_admin_orders']['types'],
  },
  'order.find_open_orders': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/admin/open',
    tokens: [
      { old: '/api/v1/order/admin/open', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/admin/open', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/admin/open', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/admin/open', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/order/admin/open', type: 0, val: 'open', end: '' },
    ],
    types: placeholder as Registry['order.find_open_orders']['types'],
  },
  'order.find_cancelled_orders': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/admin/cancelled',
    tokens: [
      { old: '/api/v1/order/admin/cancelled', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/admin/cancelled', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/admin/cancelled', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/admin/cancelled', type: 0, val: 'admin', end: '' },
      {
        old: '/api/v1/order/admin/cancelled',
        type: 0,
        val: 'cancelled',
        end: '',
      },
    ],
    types: placeholder as Registry['order.find_cancelled_orders']['types'],
  },
  'order.find_admin_issues': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/admin/issues',
    tokens: [
      { old: '/api/v1/order/admin/issues', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/admin/issues', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/admin/issues', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/admin/issues', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/order/admin/issues', type: 0, val: 'issues', end: '' },
    ],
    types: placeholder as Registry['order.find_admin_issues']['types'],
  },
  'order.find_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/:id',
    tokens: [
      { old: '/api/v1/order/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/:id', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['order.find_one']['types'],
  },
  'order.get_invoice': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/:id/invoice',
    tokens: [
      { old: '/api/v1/order/:id/invoice', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/:id/invoice', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/:id/invoice', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/:id/invoice', type: 1, val: 'id', end: '' },
      { old: '/api/v1/order/:id/invoice', type: 0, val: 'invoice', end: '' },
    ],
    types: placeholder as Registry['order.get_invoice']['types'],
  },
  'order.create_issue': {
    methods: ['POST'],
    pattern: '/api/v1/order/:id/issues',
    tokens: [
      { old: '/api/v1/order/:id/issues', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/:id/issues', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/:id/issues', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/:id/issues', type: 1, val: 'id', end: '' },
      { old: '/api/v1/order/:id/issues', type: 0, val: 'issues', end: '' },
    ],
    types: placeholder as Registry['order.create_issue']['types'],
  },
  'order.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/order/:id',
    tokens: [
      { old: '/api/v1/order/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/:id', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['order.update']['types'],
  },
  'order.update_issue': {
    methods: ['PATCH'],
    pattern: '/api/v1/order/issues/:issueId',
    tokens: [
      { old: '/api/v1/order/issues/:issueId', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/issues/:issueId', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/issues/:issueId', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/issues/:issueId', type: 0, val: 'issues', end: '' },
      {
        old: '/api/v1/order/issues/:issueId',
        type: 1,
        val: 'issueId',
        end: '',
      },
    ],
    types: placeholder as Registry['order.update_issue']['types'],
  },
  'order.refund_order': {
    methods: ['POST'],
    pattern: '/api/v1/order/admin/:id/refund',
    tokens: [
      { old: '/api/v1/order/admin/:id/refund', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/admin/:id/refund', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/admin/:id/refund', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/admin/:id/refund', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/order/admin/:id/refund', type: 1, val: 'id', end: '' },
      {
        old: '/api/v1/order/admin/:id/refund',
        type: 0,
        val: 'refund',
        end: '',
      },
    ],
    types: placeholder as Registry['order.refund_order']['types'],
  },
  'order.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/order/:id',
    tokens: [
      { old: '/api/v1/order/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/:id', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['order.remove']['types'],
  },
  'order.track': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/order/:id/track',
    tokens: [
      { old: '/api/v1/order/:id/track', type: 0, val: 'api', end: '' },
      { old: '/api/v1/order/:id/track', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/order/:id/track', type: 0, val: 'order', end: '' },
      { old: '/api/v1/order/:id/track', type: 1, val: 'id', end: '' },
      { old: '/api/v1/order/:id/track', type: 0, val: 'track', end: '' },
    ],
    types: placeholder as Registry['order.track']['types'],
  },
  'settings.get_store_settings': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/settings',
    tokens: [
      { old: '/api/v1/settings', type: 0, val: 'api', end: '' },
      { old: '/api/v1/settings', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/settings', type: 0, val: 'settings', end: '' },
    ],
    types: placeholder as Registry['settings.get_store_settings']['types'],
  },
  'settings.update_store_settings': {
    methods: ['PATCH'],
    pattern: '/api/v1/settings',
    tokens: [
      { old: '/api/v1/settings', type: 0, val: 'api', end: '' },
      { old: '/api/v1/settings', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/settings', type: 0, val: 'settings', end: '' },
    ],
    types: placeholder as Registry['settings.update_store_settings']['types'],
  },
  'review.get_featured_reviews': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/featured',
    tokens: [
      { old: '/api/v1/featured', type: 0, val: 'api', end: '' },
      { old: '/api/v1/featured', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/featured', type: 0, val: 'featured', end: '' },
    ],
    types: placeholder as Registry['review.get_featured_reviews']['types'],
  },
  'review.get_product_reviews': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/product/:productId',
    tokens: [
      { old: '/api/v1/product/:productId', type: 0, val: 'api', end: '' },
      { old: '/api/v1/product/:productId', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/product/:productId', type: 0, val: 'product', end: '' },
      { old: '/api/v1/product/:productId', type: 1, val: 'productId', end: '' },
    ],
    types: placeholder as Registry['review.get_product_reviews']['types'],
  },
  'review.get_review_eligibility': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/product/:productId/eligibility',
    tokens: [
      {
        old: '/api/v1/product/:productId/eligibility',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/product/:productId/eligibility',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/product/:productId/eligibility',
        type: 0,
        val: 'product',
        end: '',
      },
      {
        old: '/api/v1/product/:productId/eligibility',
        type: 1,
        val: 'productId',
        end: '',
      },
      {
        old: '/api/v1/product/:productId/eligibility',
        type: 0,
        val: 'eligibility',
        end: '',
      },
    ],
    types: placeholder as Registry['review.get_review_eligibility']['types'],
  },
  'review.create_review': {
    methods: ['POST'],
    pattern: '/api/v1/product/:productId',
    tokens: [
      { old: '/api/v1/product/:productId', type: 0, val: 'api', end: '' },
      { old: '/api/v1/product/:productId', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/product/:productId', type: 0, val: 'product', end: '' },
      { old: '/api/v1/product/:productId', type: 1, val: 'productId', end: '' },
    ],
    types: placeholder as Registry['review.create_review']['types'],
  },
  'review.create_comment': {
    methods: ['POST'],
    pattern: '/api/v1/:reviewId/comments',
    tokens: [
      { old: '/api/v1/:reviewId/comments', type: 0, val: 'api', end: '' },
      { old: '/api/v1/:reviewId/comments', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/:reviewId/comments', type: 1, val: 'reviewId', end: '' },
      { old: '/api/v1/:reviewId/comments', type: 0, val: 'comments', end: '' },
    ],
    types: placeholder as Registry['review.create_comment']['types'],
  },
  'review.moderate_review': {
    methods: ['PATCH'],
    pattern: '/api/v1/:id/moderate',
    tokens: [
      { old: '/api/v1/:id/moderate', type: 0, val: 'api', end: '' },
      { old: '/api/v1/:id/moderate', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/:id/moderate', type: 1, val: 'id', end: '' },
      { old: '/api/v1/:id/moderate', type: 0, val: 'moderate', end: '' },
    ],
    types: placeholder as Registry['review.moderate_review']['types'],
  },
  'review.get_pending_reviews': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/pending',
    tokens: [
      { old: '/api/v1/pending', type: 0, val: 'api', end: '' },
      { old: '/api/v1/pending', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/pending', type: 0, val: 'pending', end: '' },
    ],
    types: placeholder as Registry['review.get_pending_reviews']['types'],
  },
  'blog.upload_image': {
    methods: ['POST'],
    pattern: '/api/v1/blog/upload-image',
    tokens: [
      { old: '/api/v1/blog/upload-image', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog/upload-image', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog/upload-image', type: 0, val: 'blog', end: '' },
      {
        old: '/api/v1/blog/upload-image',
        type: 0,
        val: 'upload-image',
        end: '',
      },
    ],
    types: placeholder as Registry['blog.upload_image']['types'],
  },
  'blog.create_post': {
    methods: ['POST'],
    pattern: '/api/v1/blog',
    tokens: [
      { old: '/api/v1/blog', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog', type: 0, val: 'blog', end: '' },
    ],
    types: placeholder as Registry['blog.create_post']['types'],
  },
  'blog.get_published_posts': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/blog',
    tokens: [
      { old: '/api/v1/blog', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog', type: 0, val: 'blog', end: '' },
    ],
    types: placeholder as Registry['blog.get_published_posts']['types'],
  },
  'blog.get_all_posts': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/blog/admin/all',
    tokens: [
      { old: '/api/v1/blog/admin/all', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog/admin/all', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog/admin/all', type: 0, val: 'blog', end: '' },
      { old: '/api/v1/blog/admin/all', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/blog/admin/all', type: 0, val: 'all', end: '' },
    ],
    types: placeholder as Registry['blog.get_all_posts']['types'],
  },
  'blog.get_post_by_slug': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/blog/:slug',
    tokens: [
      { old: '/api/v1/blog/:slug', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog/:slug', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog/:slug', type: 0, val: 'blog', end: '' },
      { old: '/api/v1/blog/:slug', type: 1, val: 'slug', end: '' },
    ],
    types: placeholder as Registry['blog.get_post_by_slug']['types'],
  },
  'blog.update_post': {
    methods: ['PATCH'],
    pattern: '/api/v1/blog/:id',
    tokens: [
      { old: '/api/v1/blog/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog/:id', type: 0, val: 'blog', end: '' },
      { old: '/api/v1/blog/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['blog.update_post']['types'],
  },
  'blog.delete_post': {
    methods: ['DELETE'],
    pattern: '/api/v1/blog/:id',
    tokens: [
      { old: '/api/v1/blog/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/blog/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/blog/:id', type: 0, val: 'blog', end: '' },
      { old: '/api/v1/blog/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['blog.delete_post']['types'],
  },
  'wishlist.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/wishlist',
    tokens: [
      { old: '/api/v1/wishlist', type: 0, val: 'api', end: '' },
      { old: '/api/v1/wishlist', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/wishlist', type: 0, val: 'wishlist', end: '' },
    ],
    types: placeholder as Registry['wishlist.find_all']['types'],
  },
  'wishlist.create_guest_wishlist': {
    methods: ['POST'],
    pattern: '/api/v1/wishlist/guest-token',
    tokens: [
      { old: '/api/v1/wishlist/guest-token', type: 0, val: 'api', end: '' },
      { old: '/api/v1/wishlist/guest-token', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/wishlist/guest-token',
        type: 0,
        val: 'wishlist',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token',
        type: 0,
        val: 'guest-token',
        end: '',
      },
    ],
    types: placeholder as Registry['wishlist.create_guest_wishlist']['types'],
  },
  'wishlist.add': {
    methods: ['POST'],
    pattern: '/api/v1/wishlist/:productId',
    tokens: [
      { old: '/api/v1/wishlist/:productId', type: 0, val: 'api', end: '' },
      { old: '/api/v1/wishlist/:productId', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/wishlist/:productId', type: 0, val: 'wishlist', end: '' },
      {
        old: '/api/v1/wishlist/:productId',
        type: 1,
        val: 'productId',
        end: '',
      },
    ],
    types: placeholder as Registry['wishlist.add']['types'],
  },
  'wishlist.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/wishlist/:productId',
    tokens: [
      { old: '/api/v1/wishlist/:productId', type: 0, val: 'api', end: '' },
      { old: '/api/v1/wishlist/:productId', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/wishlist/:productId', type: 0, val: 'wishlist', end: '' },
      {
        old: '/api/v1/wishlist/:productId',
        type: 1,
        val: 'productId',
        end: '',
      },
    ],
    types: placeholder as Registry['wishlist.remove']['types'],
  },
  'wishlist.get_guest_wishlist': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/wishlist/guest-token/:token?',
    tokens: [
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'wishlist',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'guest-token',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 3,
        val: 'token',
        end: '',
      },
    ],
    types: placeholder as Registry['wishlist.get_guest_wishlist']['types'],
  },
  'wishlist.delete_guest_wishlist': {
    methods: ['DELETE'],
    pattern: '/api/v1/wishlist/guest-token/:token?',
    tokens: [
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'wishlist',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 0,
        val: 'guest-token',
        end: '',
      },
      {
        old: '/api/v1/wishlist/guest-token/:token?',
        type: 3,
        val: 'token',
        end: '',
      },
    ],
    types: placeholder as Registry['wishlist.delete_guest_wishlist']['types'],
  },
  'wishlist.merge_guest_wishlist': {
    methods: ['POST'],
    pattern: '/api/v1/wishlist/guest/merge',
    tokens: [
      { old: '/api/v1/wishlist/guest/merge', type: 0, val: 'api', end: '' },
      { old: '/api/v1/wishlist/guest/merge', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/wishlist/guest/merge',
        type: 0,
        val: 'wishlist',
        end: '',
      },
      { old: '/api/v1/wishlist/guest/merge', type: 0, val: 'guest', end: '' },
      { old: '/api/v1/wishlist/guest/merge', type: 0, val: 'merge', end: '' },
    ],
    types: placeholder as Registry['wishlist.merge_guest_wishlist']['types'],
  },
  'coupon.validate': {
    methods: ['POST'],
    pattern: '/api/v1/coupons/validate',
    tokens: [
      { old: '/api/v1/coupons/validate', type: 0, val: 'api', end: '' },
      { old: '/api/v1/coupons/validate', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/coupons/validate', type: 0, val: 'coupons', end: '' },
      { old: '/api/v1/coupons/validate', type: 0, val: 'validate', end: '' },
    ],
    types: placeholder as Registry['coupon.validate']['types'],
  },
  'coupon.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/coupons',
    tokens: [
      { old: '/api/v1/coupons', type: 0, val: 'api', end: '' },
      { old: '/api/v1/coupons', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/coupons', type: 0, val: 'coupons', end: '' },
    ],
    types: placeholder as Registry['coupon.find_all']['types'],
  },
  'coupon.get_analytics': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/coupons/analytics',
    tokens: [
      { old: '/api/v1/coupons/analytics', type: 0, val: 'api', end: '' },
      { old: '/api/v1/coupons/analytics', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/coupons/analytics', type: 0, val: 'coupons', end: '' },
      { old: '/api/v1/coupons/analytics', type: 0, val: 'analytics', end: '' },
    ],
    types: placeholder as Registry['coupon.get_analytics']['types'],
  },
  'coupon.create': {
    methods: ['POST'],
    pattern: '/api/v1/coupons',
    tokens: [
      { old: '/api/v1/coupons', type: 0, val: 'api', end: '' },
      { old: '/api/v1/coupons', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/coupons', type: 0, val: 'coupons', end: '' },
    ],
    types: placeholder as Registry['coupon.create']['types'],
  },
  'coupon.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/coupons/:id',
    tokens: [
      { old: '/api/v1/coupons/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/coupons/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/coupons/:id', type: 0, val: 'coupons', end: '' },
      { old: '/api/v1/coupons/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['coupon.update']['types'],
  },
  'coupon.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/coupons/:id',
    tokens: [
      { old: '/api/v1/coupons/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/coupons/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/coupons/:id', type: 0, val: 'coupons', end: '' },
      { old: '/api/v1/coupons/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['coupon.remove']['types'],
  },
  'admin.get_overview': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/overview',
    tokens: [
      { old: '/api/v1/overview', type: 0, val: 'api', end: '' },
      { old: '/api/v1/overview', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/overview', type: 0, val: 'overview', end: '' },
    ],
    types: placeholder as Registry['admin.get_overview']['types'],
  },
  'admin.list_users': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/admin/users',
    tokens: [
      { old: '/api/v1/admin/users', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/users', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/users', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/users', type: 0, val: 'users', end: '' },
    ],
    types: placeholder as Registry['admin.list_users']['types'],
  },
  'admin.get_user': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/admin/users/:id',
    tokens: [
      { old: '/api/v1/admin/users/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'users', end: '' },
      { old: '/api/v1/admin/users/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['admin.get_user']['types'],
  },
  'admin.update_user': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/users/:id',
    tokens: [
      { old: '/api/v1/admin/users/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'users', end: '' },
      { old: '/api/v1/admin/users/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['admin.update_user']['types'],
  },
  'admin.delete_user': {
    methods: ['DELETE'],
    pattern: '/api/v1/admin/users/:id',
    tokens: [
      { old: '/api/v1/admin/users/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/users/:id', type: 0, val: 'users', end: '' },
      { old: '/api/v1/admin/users/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['admin.delete_user']['types'],
  },
  'admin.list_orders': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/admin/orders',
    tokens: [
      { old: '/api/v1/admin/orders', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/orders', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/orders', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/orders', type: 0, val: 'orders', end: '' },
    ],
    types: placeholder as Registry['admin.list_orders']['types'],
  },
  'admin.list_pending_products': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/admin/products/pending',
    tokens: [
      { old: '/api/v1/admin/products/pending', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/products/pending', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/products/pending', type: 0, val: 'admin', end: '' },
      {
        old: '/api/v1/admin/products/pending',
        type: 0,
        val: 'products',
        end: '',
      },
      {
        old: '/api/v1/admin/products/pending',
        type: 0,
        val: 'pending',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.list_pending_products']['types'],
  },
  'admin.approve_product': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/products/:id/approve',
    tokens: [
      {
        old: '/api/v1/admin/products/:id/approve',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/admin/products/:id/approve',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/admin/products/:id/approve',
        type: 0,
        val: 'admin',
        end: '',
      },
      {
        old: '/api/v1/admin/products/:id/approve',
        type: 0,
        val: 'products',
        end: '',
      },
      {
        old: '/api/v1/admin/products/:id/approve',
        type: 1,
        val: 'id',
        end: '',
      },
      {
        old: '/api/v1/admin/products/:id/approve',
        type: 0,
        val: 'approve',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.approve_product']['types'],
  },
  'admin.reject_product': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/products/:id/reject',
    tokens: [
      {
        old: '/api/v1/admin/products/:id/reject',
        type: 0,
        val: 'api',
        end: '',
      },
      { old: '/api/v1/admin/products/:id/reject', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/admin/products/:id/reject',
        type: 0,
        val: 'admin',
        end: '',
      },
      {
        old: '/api/v1/admin/products/:id/reject',
        type: 0,
        val: 'products',
        end: '',
      },
      { old: '/api/v1/admin/products/:id/reject', type: 1, val: 'id', end: '' },
      {
        old: '/api/v1/admin/products/:id/reject',
        type: 0,
        val: 'reject',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.reject_product']['types'],
  },
  'admin.list_pending_reviews': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/admin/reviews/pending',
    tokens: [
      { old: '/api/v1/admin/reviews/pending', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/reviews/pending', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/reviews/pending', type: 0, val: 'admin', end: '' },
      {
        old: '/api/v1/admin/reviews/pending',
        type: 0,
        val: 'reviews',
        end: '',
      },
      {
        old: '/api/v1/admin/reviews/pending',
        type: 0,
        val: 'pending',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.list_pending_reviews']['types'],
  },
  'admin.approve_review': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/reviews/:id/approve',
    tokens: [
      {
        old: '/api/v1/admin/reviews/:id/approve',
        type: 0,
        val: 'api',
        end: '',
      },
      { old: '/api/v1/admin/reviews/:id/approve', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/admin/reviews/:id/approve',
        type: 0,
        val: 'admin',
        end: '',
      },
      {
        old: '/api/v1/admin/reviews/:id/approve',
        type: 0,
        val: 'reviews',
        end: '',
      },
      { old: '/api/v1/admin/reviews/:id/approve', type: 1, val: 'id', end: '' },
      {
        old: '/api/v1/admin/reviews/:id/approve',
        type: 0,
        val: 'approve',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.approve_review']['types'],
  },
  'admin.reject_review': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/reviews/:id/reject',
    tokens: [
      { old: '/api/v1/admin/reviews/:id/reject', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/reviews/:id/reject', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/admin/reviews/:id/reject',
        type: 0,
        val: 'admin',
        end: '',
      },
      {
        old: '/api/v1/admin/reviews/:id/reject',
        type: 0,
        val: 'reviews',
        end: '',
      },
      { old: '/api/v1/admin/reviews/:id/reject', type: 1, val: 'id', end: '' },
      {
        old: '/api/v1/admin/reviews/:id/reject',
        type: 0,
        val: 'reject',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.reject_review']['types'],
  },
  'admin.list_pending_blog_posts': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/admin/blog/pending',
    tokens: [
      { old: '/api/v1/admin/blog/pending', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/blog/pending', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/blog/pending', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/blog/pending', type: 0, val: 'blog', end: '' },
      { old: '/api/v1/admin/blog/pending', type: 0, val: 'pending', end: '' },
    ],
    types: placeholder as Registry['admin.list_pending_blog_posts']['types'],
  },
  'admin.publish_blog_post': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/blog/:id/publish',
    tokens: [
      { old: '/api/v1/admin/blog/:id/publish', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/blog/:id/publish', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/admin/blog/:id/publish', type: 0, val: 'admin', end: '' },
      { old: '/api/v1/admin/blog/:id/publish', type: 0, val: 'blog', end: '' },
      { old: '/api/v1/admin/blog/:id/publish', type: 1, val: 'id', end: '' },
      {
        old: '/api/v1/admin/blog/:id/publish',
        type: 0,
        val: 'publish',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.publish_blog_post']['types'],
  },
  'admin.unpublish_blog_post': {
    methods: ['PATCH'],
    pattern: '/api/v1/admin/blog/:id/unpublish',
    tokens: [
      { old: '/api/v1/admin/blog/:id/unpublish', type: 0, val: 'api', end: '' },
      { old: '/api/v1/admin/blog/:id/unpublish', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/admin/blog/:id/unpublish',
        type: 0,
        val: 'admin',
        end: '',
      },
      {
        old: '/api/v1/admin/blog/:id/unpublish',
        type: 0,
        val: 'blog',
        end: '',
      },
      { old: '/api/v1/admin/blog/:id/unpublish', type: 1, val: 'id', end: '' },
      {
        old: '/api/v1/admin/blog/:id/unpublish',
        type: 0,
        val: 'unpublish',
        end: '',
      },
    ],
    types: placeholder as Registry['admin.unpublish_blog_post']['types'],
  },
  'health.check': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/health',
    tokens: [
      { old: '/api/v1/health', type: 0, val: 'api', end: '' },
      { old: '/api/v1/health', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/health', type: 0, val: 'health', end: '' },
    ],
    types: placeholder as Registry['health.check']['types'],
  },
  'health.ready': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/health/ready',
    tokens: [
      { old: '/api/v1/health/ready', type: 0, val: 'api', end: '' },
      { old: '/api/v1/health/ready', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/health/ready', type: 0, val: 'health', end: '' },
      { old: '/api/v1/health/ready', type: 0, val: 'ready', end: '' },
    ],
    types: placeholder as Registry['health.ready']['types'],
  },
  'health.live': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/health/live',
    tokens: [
      { old: '/api/v1/health/live', type: 0, val: 'api', end: '' },
      { old: '/api/v1/health/live', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/health/live', type: 0, val: 'health', end: '' },
      { old: '/api/v1/health/live', type: 0, val: 'live', end: '' },
    ],
    types: placeholder as Registry['health.live']['types'],
  },
  'audit.get_audit_logs': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/log',
    tokens: [
      { old: '/api/v1/log', type: 0, val: 'api', end: '' },
      { old: '/api/v1/log', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/log', type: 0, val: 'log', end: '' },
    ],
    types: placeholder as Registry['audit.get_audit_logs']['types'],
  },
  'audit.get_audit_log': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/log/:id',
    tokens: [
      { old: '/api/v1/log/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/log/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/log/:id', type: 0, val: 'log', end: '' },
      { old: '/api/v1/log/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['audit.get_audit_log']['types'],
  },
  'analytics.get_sales_stats': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/sales/stats',
    tokens: [
      { old: '/api/v1/sales/stats', type: 0, val: 'api', end: '' },
      { old: '/api/v1/sales/stats', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/sales/stats', type: 0, val: 'sales', end: '' },
      { old: '/api/v1/sales/stats', type: 0, val: 'stats', end: '' },
    ],
    types: placeholder as Registry['analytics.get_sales_stats']['types'],
  },
  'analytics.get_orders_overview': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/orders/overview',
    tokens: [
      { old: '/api/v1/orders/overview', type: 0, val: 'api', end: '' },
      { old: '/api/v1/orders/overview', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/orders/overview', type: 0, val: 'orders', end: '' },
      { old: '/api/v1/orders/overview', type: 0, val: 'overview', end: '' },
    ],
    types: placeholder as Registry['analytics.get_orders_overview']['types'],
  },
  'analytics.get_recoverable_carts': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/abandoned-carts/recoverable',
    tokens: [
      {
        old: '/api/v1/abandoned-carts/recoverable',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/abandoned-carts/recoverable',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/abandoned-carts/recoverable',
        type: 0,
        val: 'abandoned-carts',
        end: '',
      },
      {
        old: '/api/v1/abandoned-carts/recoverable',
        type: 0,
        val: 'recoverable',
        end: '',
      },
    ],
    types: placeholder as Registry['analytics.get_recoverable_carts']['types'],
  },
  'analytics.run_abandoned_cart_sweep': {
    methods: ['POST'],
    pattern: '/api/v1/abandoned-carts/sweep',
    tokens: [
      { old: '/api/v1/abandoned-carts/sweep', type: 0, val: 'api', end: '' },
      { old: '/api/v1/abandoned-carts/sweep', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/abandoned-carts/sweep',
        type: 0,
        val: 'abandoned-carts',
        end: '',
      },
      { old: '/api/v1/abandoned-carts/sweep', type: 0, val: 'sweep', end: '' },
    ],
    types:
      placeholder as Registry['analytics.run_abandoned_cart_sweep']['types'],
  },
  'analytics.record_view': {
    methods: ['POST'],
    pattern: '/api/v1/viewed',
    tokens: [
      { old: '/api/v1/viewed', type: 0, val: 'api', end: '' },
      { old: '/api/v1/viewed', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/viewed', type: 0, val: 'viewed', end: '' },
    ],
    types: placeholder as Registry['analytics.record_view']['types'],
  },
  'analytics.get_recently_viewed': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/viewed',
    tokens: [
      { old: '/api/v1/viewed', type: 0, val: 'api', end: '' },
      { old: '/api/v1/viewed', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/viewed', type: 0, val: 'viewed', end: '' },
    ],
    types: placeholder as Registry['analytics.get_recently_viewed']['types'],
  },
  'analytics.clear_history': {
    methods: ['DELETE'],
    pattern: '/api/v1/viewed',
    tokens: [
      { old: '/api/v1/viewed', type: 0, val: 'api', end: '' },
      { old: '/api/v1/viewed', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/viewed', type: 0, val: 'viewed', end: '' },
    ],
    types: placeholder as Registry['analytics.clear_history']['types'],
  },
  'hero.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/hero',
    tokens: [
      { old: '/api/v1/hero', type: 0, val: 'api', end: '' },
      { old: '/api/v1/hero', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/hero', type: 0, val: 'hero', end: '' },
    ],
    types: placeholder as Registry['hero.find_all']['types'],
  },
  'hero.find_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/hero/:id',
    tokens: [
      { old: '/api/v1/hero/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/hero/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/hero/:id', type: 0, val: 'hero', end: '' },
      { old: '/api/v1/hero/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['hero.find_one']['types'],
  },
  'hero.create': {
    methods: ['POST'],
    pattern: '/api/v1/hero',
    tokens: [
      { old: '/api/v1/hero', type: 0, val: 'api', end: '' },
      { old: '/api/v1/hero', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/hero', type: 0, val: 'hero', end: '' },
    ],
    types: placeholder as Registry['hero.create']['types'],
  },
  'hero.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/hero/:id',
    tokens: [
      { old: '/api/v1/hero/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/hero/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/hero/:id', type: 0, val: 'hero', end: '' },
      { old: '/api/v1/hero/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['hero.update']['types'],
  },
  'hero.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/hero/:id',
    tokens: [
      { old: '/api/v1/hero/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/hero/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/hero/:id', type: 0, val: 'hero', end: '' },
      { old: '/api/v1/hero/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['hero.remove']['types'],
  },
  'new_arrival.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/new-arrivals',
    tokens: [
      { old: '/api/v1/new-arrivals', type: 0, val: 'api', end: '' },
      { old: '/api/v1/new-arrivals', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/new-arrivals', type: 0, val: 'new-arrivals', end: '' },
    ],
    types: placeholder as Registry['new_arrival.find_all']['types'],
  },
  'new_arrival.find_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/new-arrivals/:id',
    tokens: [
      { old: '/api/v1/new-arrivals/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/new-arrivals/:id', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/new-arrivals/:id',
        type: 0,
        val: 'new-arrivals',
        end: '',
      },
      { old: '/api/v1/new-arrivals/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['new_arrival.find_one']['types'],
  },
  'new_arrival.create': {
    methods: ['POST'],
    pattern: '/api/v1/new-arrivals',
    tokens: [
      { old: '/api/v1/new-arrivals', type: 0, val: 'api', end: '' },
      { old: '/api/v1/new-arrivals', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/new-arrivals', type: 0, val: 'new-arrivals', end: '' },
    ],
    types: placeholder as Registry['new_arrival.create']['types'],
  },
  'new_arrival.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/new-arrivals/:id',
    tokens: [
      { old: '/api/v1/new-arrivals/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/new-arrivals/:id', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/new-arrivals/:id',
        type: 0,
        val: 'new-arrivals',
        end: '',
      },
      { old: '/api/v1/new-arrivals/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['new_arrival.update']['types'],
  },
  'new_arrival.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/new-arrivals/:id',
    tokens: [
      { old: '/api/v1/new-arrivals/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/new-arrivals/:id', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/new-arrivals/:id',
        type: 0,
        val: 'new-arrivals',
        end: '',
      },
      { old: '/api/v1/new-arrivals/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['new_arrival.remove']['types'],
  },
  'gift_card.redeem': {
    methods: ['POST'],
    pattern: '/api/v1/gift-cards/redeem',
    tokens: [
      { old: '/api/v1/gift-cards/redeem', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards/redeem', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/gift-cards/redeem', type: 0, val: 'gift-cards', end: '' },
      { old: '/api/v1/gift-cards/redeem', type: 0, val: 'redeem', end: '' },
    ],
    types: placeholder as Registry['gift_card.redeem']['types'],
  },
  'gift_card.balance': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/gift-cards/balance',
    tokens: [
      { old: '/api/v1/gift-cards/balance', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards/balance', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/gift-cards/balance',
        type: 0,
        val: 'gift-cards',
        end: '',
      },
      { old: '/api/v1/gift-cards/balance', type: 0, val: 'balance', end: '' },
    ],
    types: placeholder as Registry['gift_card.balance']['types'],
  },
  'gift_card.find_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/gift-cards',
    tokens: [
      { old: '/api/v1/gift-cards', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/gift-cards', type: 0, val: 'gift-cards', end: '' },
    ],
    types: placeholder as Registry['gift_card.find_all']['types'],
  },
  'gift_card.find_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/gift-cards/:id',
    tokens: [
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'gift-cards', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['gift_card.find_one']['types'],
  },
  'gift_card.create': {
    methods: ['POST'],
    pattern: '/api/v1/gift-cards',
    tokens: [
      { old: '/api/v1/gift-cards', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/gift-cards', type: 0, val: 'gift-cards', end: '' },
    ],
    types: placeholder as Registry['gift_card.create']['types'],
  },
  'gift_card.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/gift-cards/:id',
    tokens: [
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'gift-cards', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['gift_card.update']['types'],
  },
  'gift_card.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/gift-cards/:id',
    tokens: [
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 0, val: 'gift-cards', end: '' },
      { old: '/api/v1/gift-cards/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['gift_card.remove']['types'],
  },
  'notification.get_user_notifications': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/notifications',
    tokens: [
      { old: '/api/v1/notifications', type: 0, val: 'api', end: '' },
      { old: '/api/v1/notifications', type: 0, val: 'v1', end: '' },
      { old: '/api/v1/notifications', type: 0, val: 'notifications', end: '' },
    ],
    types:
      placeholder as Registry['notification.get_user_notifications']['types'],
  },
  'notification.get_unread_count': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/notifications/unread-count',
    tokens: [
      {
        old: '/api/v1/notifications/unread-count',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/notifications/unread-count',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/notifications/unread-count',
        type: 0,
        val: 'notifications',
        end: '',
      },
      {
        old: '/api/v1/notifications/unread-count',
        type: 0,
        val: 'unread-count',
        end: '',
      },
    ],
    types: placeholder as Registry['notification.get_unread_count']['types'],
  },
  'notification.mark_notification_as_read': {
    methods: ['PATCH'],
    pattern: '/api/v1/notifications/:id/read',
    tokens: [
      { old: '/api/v1/notifications/:id/read', type: 0, val: 'api', end: '' },
      { old: '/api/v1/notifications/:id/read', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/notifications/:id/read',
        type: 0,
        val: 'notifications',
        end: '',
      },
      { old: '/api/v1/notifications/:id/read', type: 1, val: 'id', end: '' },
      { old: '/api/v1/notifications/:id/read', type: 0, val: 'read', end: '' },
    ],
    types:
      placeholder as Registry['notification.mark_notification_as_read']['types'],
  },
  'notification.mark_all_notifications_as_read': {
    methods: ['PATCH'],
    pattern: '/api/v1/notifications/read-all',
    tokens: [
      { old: '/api/v1/notifications/read-all', type: 0, val: 'api', end: '' },
      { old: '/api/v1/notifications/read-all', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/notifications/read-all',
        type: 0,
        val: 'notifications',
        end: '',
      },
      {
        old: '/api/v1/notifications/read-all',
        type: 0,
        val: 'read-all',
        end: '',
      },
    ],
    types:
      placeholder as Registry['notification.mark_all_notifications_as_read']['types'],
  },
  'notification.get_user_preferences': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/notifications/preferences',
    tokens: [
      {
        old: '/api/v1/notifications/preferences',
        type: 0,
        val: 'api',
        end: '',
      },
      { old: '/api/v1/notifications/preferences', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/notifications/preferences',
        type: 0,
        val: 'notifications',
        end: '',
      },
      {
        old: '/api/v1/notifications/preferences',
        type: 0,
        val: 'preferences',
        end: '',
      },
    ],
    types:
      placeholder as Registry['notification.get_user_preferences']['types'],
  },
  'notification.update_notification_preference': {
    methods: ['PATCH'],
    pattern: '/api/v1/notifications/preferences',
    tokens: [
      {
        old: '/api/v1/notifications/preferences',
        type: 0,
        val: 'api',
        end: '',
      },
      { old: '/api/v1/notifications/preferences', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/notifications/preferences',
        type: 0,
        val: 'notifications',
        end: '',
      },
      {
        old: '/api/v1/notifications/preferences',
        type: 0,
        val: 'preferences',
        end: '',
      },
    ],
    types:
      placeholder as Registry['notification.update_notification_preference']['types'],
  },
  'notification.find_admin_notifications': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/notifications/admin',
    tokens: [
      { old: '/api/v1/notifications/admin', type: 0, val: 'api', end: '' },
      { old: '/api/v1/notifications/admin', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/notifications/admin',
        type: 0,
        val: 'notifications',
        end: '',
      },
      { old: '/api/v1/notifications/admin', type: 0, val: 'admin', end: '' },
    ],
    types:
      placeholder as Registry['notification.find_admin_notifications']['types'],
  },
  'notification.get_health': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/notifications/admin/health',
    tokens: [
      {
        old: '/api/v1/notifications/admin/health',
        type: 0,
        val: 'api',
        end: '',
      },
      {
        old: '/api/v1/notifications/admin/health',
        type: 0,
        val: 'v1',
        end: '',
      },
      {
        old: '/api/v1/notifications/admin/health',
        type: 0,
        val: 'notifications',
        end: '',
      },
      {
        old: '/api/v1/notifications/admin/health',
        type: 0,
        val: 'admin',
        end: '',
      },
      {
        old: '/api/v1/notifications/admin/health',
        type: 0,
        val: 'health',
        end: '',
      },
    ],
    types: placeholder as Registry['notification.get_health']['types'],
  },
  'email_template.get_all': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/email-templates',
    tokens: [
      { old: '/api/v1/email-templates', type: 0, val: 'api', end: '' },
      { old: '/api/v1/email-templates', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/email-templates',
        type: 0,
        val: 'email-templates',
        end: '',
      },
    ],
    types: placeholder as Registry['email_template.get_all']['types'],
  },
  'email_template.get_one': {
    methods: ['GET', 'HEAD'],
    pattern: '/api/v1/email-templates/:id',
    tokens: [
      { old: '/api/v1/email-templates/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/email-templates/:id', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/email-templates/:id',
        type: 0,
        val: 'email-templates',
        end: '',
      },
      { old: '/api/v1/email-templates/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['email_template.get_one']['types'],
  },
  'email_template.create': {
    methods: ['POST'],
    pattern: '/api/v1/email-templates',
    tokens: [
      { old: '/api/v1/email-templates', type: 0, val: 'api', end: '' },
      { old: '/api/v1/email-templates', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/email-templates',
        type: 0,
        val: 'email-templates',
        end: '',
      },
    ],
    types: placeholder as Registry['email_template.create']['types'],
  },
  'email_template.update': {
    methods: ['PATCH'],
    pattern: '/api/v1/email-templates/:id',
    tokens: [
      { old: '/api/v1/email-templates/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/email-templates/:id', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/email-templates/:id',
        type: 0,
        val: 'email-templates',
        end: '',
      },
      { old: '/api/v1/email-templates/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['email_template.update']['types'],
  },
  'email_template.remove': {
    methods: ['DELETE'],
    pattern: '/api/v1/email-templates/:id',
    tokens: [
      { old: '/api/v1/email-templates/:id', type: 0, val: 'api', end: '' },
      { old: '/api/v1/email-templates/:id', type: 0, val: 'v1', end: '' },
      {
        old: '/api/v1/email-templates/:id',
        type: 0,
        val: 'email-templates',
        end: '',
      },
      { old: '/api/v1/email-templates/:id', type: 1, val: 'id', end: '' },
    ],
    types: placeholder as Registry['email_template.remove']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>;

export { routes };

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
};

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes;
    $tree: ApiDefinition;
  }
}
